name: Python Checks

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    name: python tests on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['macOS-latest', 'ubuntu-latest']
        python-version: ['3.6', '3.7', '3.8']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: flink-ml-python/dev
        run: python -m pip install -r dev-requirements.txt
      - name: Check code style
        working-directory: flink-ml-python
        run: python -m flake8 --config=setup.cfg
      - name: Check type annotations
        working-directory: flink-ml-python
        run: python -m mypy --config=setup.cfg
      - name: Test the source code
        working-directory: flink-ml-python
        run: pytest


